name: mirroir

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@github.com:Chsfdjr/mirror_bschocolatine.git
          ssh_private_key:
            secrets.SECRET