name: chocolatine

on:
  push:
    branches-ignore : "-ga-ignore-"
  pull_request:
    branches-ignore : "-ga-ignore-"

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-MLH-2-1-chocolatine-chris.fordjour.git
  EXECUTABLES: "run-tests"
jobs:
  job_checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: display branch name
      run: echo 
    - name: command
      run: du -skh --exclude=".git"
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - name: check_coding_style
      run: check.sh $(pwd) $(pwd)
  check_program_compilation:
     runs-on: ubuntu-latest
     steps:
     - name: lauch make
       run: make $(pwd)
     - name: check ls
       run: ls | echo
       timeout-minutes: 2
     - name: lauch make clean
       run: make clean $(pwd)
       timeout-minutes: 2
     - name: Annotations Action
       uses: Attest/annotations-action@v1.0.3

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: run_tests
      run: make ${{ env.EXECUTABLES}}
      timeout-minutes: 2
  job_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL}}
          ssh_private_key:
            ${{ secrets.SECRET_NEW_KEY }}

