name: chocolatine

on: [push, pull_request]

jobs:
  job_checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: display branch name
      run: echo 
    - name: command
      run: du -skh --exclude=".git"
  # check_coding_style:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: check_coding_style
  #     uses: ghcr.io/epitech/coding-style-checker:latest
  #     run: check.sh $(pwd) $(pwd)
  check_program_compilation:
     runs-on: ubuntu-latest
     steps:
     - name: lauch make
       run: make
       timeout-minutes: 2
     - name: lauch make clean
       run: make clean
       timeout-minutes: 2
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: run_tests
      run: make tests_run
      timeout-minutes: 2
  job_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2027/B-DOP-200-MLH-2-1-chocolatine-chris.fordjour.git
          ssh_private_key:
            ${{ secrets.SECRET_NEW_KEY }}
  # push_to_mirror:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   steps:
  #   - name: run_tests
  #     run:
